// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe2F7HPPE_zCHx-2dkLJPd-5lR87AYA_k',
    appId: '1:1004762498185:web:52d66b91ed01aa7c263258',
    messagingSenderId: '1004762498185',
    projectId: 'flutter-food-quality-tracking',
    authDomain: 'flutter-food-quality-tracking.firebaseapp.com',
    storageBucket: 'flutter-food-quality-tracking.appspot.com',
    measurementId: 'G-GR72QWEQDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMYK7hmF-BFi3guhF543dTgLfWFQcuITs',
    appId: '1:1004762498185:android:66e57eec0593da08263258',
    messagingSenderId: '1004762498185',
    projectId: 'flutter-food-quality-tracking',
    storageBucket: 'flutter-food-quality-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4AyslEiK3E4KnrtGdMpHyr9VvBLcwvSE',
    appId: '1:1004762498185:ios:744b7db4447ee266263258',
    messagingSenderId: '1004762498185',
    projectId: 'flutter-food-quality-tracking',
    storageBucket: 'flutter-food-quality-tracking.appspot.com',
    iosClientId: '1004762498185-50668qbklu0if54esajm00p89eldrtjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCwFoodQualityTrackingSystem',
  );
}
